language: java

sudo: false

addons:
  hosts:
    - db

services:
  - docker

install:
  - mvn clean install -DskipTests=true -D"maven.javadoc.skip=true" -B -V

before_script:
  - mvn clean

jobs:
  include:
    - stage: Units Tests
      install: skip
      script:
        - mvn test -Dtest="com.napier.sem.places.*Test"



    - stage: deploy
      install: skip
      jdk: oraclejdk11
      script: echo "Deploy"