language: java

sudo: false

addons:
  hosts:
    - db

jdk:
  - openjdk11

services:
  - docker

install:
  - mvn clean install -DskipTests=true -D"maven.javadoc.skip=true" -B -V


jobs:
  include:
    - stage: unit tests
      install: skip
      script: mvn test -Dtest=com.napier.sem.places.*Test
    - stage: Integration
      script:
          - sudo docker build -t db db
          - sudo docker run --rm -d -p 3306:3306 db
          - mvn test -Dtest="com.napier.sem.utils.AppTest"
    - stage: deploy
      install: skip
      jdk: oraclejdk11
      script: echo "Deploy"

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop

stages:
  - unit tests
  - Integration
  - name: deploy
    if: branch = master

after_success:
  - bash <(curl -s https://codecov.io/bash)