@startuml

actor RC as "Report Coordinator"
rectangle "System" {
    usecase UC1 as "Country Report"
    usecase UC2 as "City Report"
    usecase UC3 as "Population Report"
    usecase UC4 as "Capital City Report"
    usecase UC5 as "Addition Report"
RC--UC1
RC--UC2
RC--UC3
RC--UC4
RC--UC5
}

@enduml